//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skype.Extension.Utils {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UserStatusResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserStatusResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Skype.Extension.Utils.UserStatusResources", typeof(UserStatusResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap awaySmall {
            get {
                object obj = ResourceManager.GetObject("awaySmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Away.
        /// </summary>
        internal static string cusAway {
            get {
                return ResourceManager.GetString("cusAway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do Not Disturb.
        /// </summary>
        internal static string cusDoNotDisturb {
            get {
                return ResourceManager.GetString("cusDoNotDisturb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invisible.
        /// </summary>
        internal static string cusInvisible {
            get {
                return ResourceManager.GetString("cusInvisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged Out.
        /// </summary>
        internal static string cusLoggedOut {
            get {
                return ResourceManager.GetString("cusLoggedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Available.
        /// </summary>
        internal static string cusNotAvailable {
            get {
                return ResourceManager.GetString("cusNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        internal static string cusOffline {
            get {
                return ResourceManager.GetString("cusOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        internal static string cusOnline {
            get {
                return ResourceManager.GetString("cusOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SkypeMe!.
        /// </summary>
        internal static string cusSkypeMe {
            get {
                return ResourceManager.GetString("cusSkypeMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string cusUnknown {
            get {
                return ResourceManager.GetString("cusUnknown", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap dndSmall {
            get {
                object obj = ResourceManager.GetObject("dndSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap invisibleSmall {
            get {
                object obj = ResourceManager.GetObject("invisibleSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap loggedoutSmall {
            get {
                object obj = ResourceManager.GetObject("loggedoutSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap naSmall {
            get {
                object obj = ResourceManager.GetObject("naSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap onlineSmall {
            get {
                object obj = ResourceManager.GetObject("onlineSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap skypemeSmall {
            get {
                object obj = ResourceManager.GetObject("skypemeSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap unknownSmall {
            get {
                object obj = ResourceManager.GetObject("unknownSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
