//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InACall.Plugin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InACall.Plugin.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change user status to.
        /// </summary>
        internal static string AllowChangeStatusText {
            get {
                return ResourceManager.GetString("AllowChangeStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string btnCancelText {
            get {
                return ResourceManager.GetString("btnCancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string btnOkText {
            get {
                return ResourceManager.GetString("btnOkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m on the call.
        /// </summary>
        internal static string DefaultMoodText {
            get {
                return ResourceManager.GetString("DefaultMoodText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not change user status.
        /// </summary>
        internal static string DoNotChangeStatusText {
            get {
                return ResourceManager.GetString("DoNotChangeStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change settings to indicate that you are in a call.
        /// </summary>
        internal static string headerText {
            get {
                return ResourceManager.GetString("headerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy me a beer.
        /// </summary>
        internal static string linkLabelText {
            get {
                return ResourceManager.GetString("linkLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InACall Indicator Settings....
        /// </summary>
        internal static string mnuSettings {
            get {
                return ResourceManager.GetString("mnuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens configuration dialog of the InACall plugin.
        /// </summary>
        internal static string mnuSettingsHint {
            get {
                return ResourceManager.GetString("mnuSettingsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change mood text to.
        /// </summary>
        internal static string rbtAllowMoodChangeText {
            get {
                return ResourceManager.GetString("rbtAllowMoodChangeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not change mood text.
        /// </summary>
        internal static string rbtNoMoodChangeText {
            get {
                return ResourceManager.GetString("rbtNoMoodChangeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remain Invisible.
        /// </summary>
        internal static string RemainInvisibleText {
            get {
                return ResourceManager.GetString("RemainInvisibleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InACall Indicator Setup.
        /// </summary>
        internal static string SettingsFormText {
            get {
                return ResourceManager.GetString("SettingsFormText", resourceCulture);
            }
        }
    }
}
